console.log("mon test");
var obj = {
dedut : [
    "Repose-toi quelques heure",
    "Prends tout ton temps",
    "Va dormir",
    "Nettoie tes yeux",
    "Lave tes oreilles",
    "Bande-toi les yeux",
    "Cure tes dents",
    "Rince-toi la bouche",
    "Va faire un footing",
    "Pour mieux comprendre, médite",
    "Sèche tes cheveux",
    "Va cueillir des fleurs",
    "Respire et ouvre ton esprit",
    "Avale-toi un cocktail",
    "Va faire un point sur ta vie",
    "Fais un exercice respiratoire",
    "Prends un instant de réflexion",
    "Pose toi la question",
    "Fais-toi un sandwich",
    "Va faire de la plongée",
    "Va prendre une douche",
    "Prépare-toi un nid douillet",
    "Va jouer à la marelle",
    "Fait le plein de vitamine",
    ],
fin : [
    "et va courrir sur l'autoroute.",
    "dans une bétonnière.",
    "dans une coulée de lave.",
    "dans un couloir d'avalanche.",
    "avec du gravier.",
    "avec une poire à lavement.",
    "et ne t'arrête surtout pas.",
    "avec un jet d'acide.",
    "dans un champs de mines.",
    "avec une tondeuse.",
    "avec une perceuse.",
    "dans un four à micro-onde.",
    "avec des boulons.",
    "dans les parages de Tchernobyl.",
    "avec les doigts dans la prise.",
    "avec le bout pointu.",
    "en courant avec des ciseaux.",
    "avec les pieds dans le ciment.",
    "et ne reviens jamais.",
    "jusqu'à ce qu'il n'y en ait plus.",
    "sans les mains.",
    "et attends qu'on t'appelle.",
    "en comptant jusqu'à l'infini.",
    ]
}

console.log(obj);
